name: data_augment
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.11.0
  - aiohttp=3.6.3
  - astor=0.8.1
  - async-timeout=3.0.1
  - attrs=20.3.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.3.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.2
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - idna=2.10
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - libprotobuf=3.14.0
  - markdown=3.3.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.6
  - oauthlib=3.1.0
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - pip=20.3.3
  - protobuf=3.14.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.7.9
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7
  - scipy=1.6.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=0.16.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.12.1
  - yarl=1.6.3
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
    - astunparse==1.6.3
    - gast==0.3.3
    - numpy==1.18.5
    - tensorflow-gpu==2.3.1
    - tensorflow-gpu-estimator==2.3.0
